-- Add migration script here

CREATE TABLE IF NOT EXISTS tts (
    id  TEXT    PRIMARY KEY NOT NULL ,
    path    TEXT    NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    time    REAL NOT NULL,
    ocr_id TEXT NOT NULL,
    voice   TEXT NOT NULL CHECK (voice IN (
  'af_heart', 
  'af_alloy',
  'af_aoede',
  'af_bella',
  'af_jessica',
  'af_kore',
  'af_nicole',
  'af_nova',
  'af_river',
  'af_sarah',
  'af_sky',
  'am_adam',
  'am_echo',
  'am_eric',
  'am_fenrir',
  'am_liam',
  'am_michael',
  'am_onyx',
  'am_puck',
  'bf_alice',
  'bf_emma',
  'bf_isabella',
  'bf_lily',
  'bm_daniel',
  'bm_fable',
  'bm_george',
  'bm_lewis')),
    speed REAL NOT NULL DEFAULT 1.0 CHECK (speed BETWEEN 0.5 AND 2.0),
    FOREIGN KEY (ocr_id) REFERENCES ocr_text(id) ON DELETE CASCADE 
)
