name: Windows Build

on:
  push:
    branches:
      - windows

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create resource directory
        run: mkdir src-tauri\models
        
      - name: Download Kokoro model
        run: |
          curl -L "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/kokoro-v1.0.fp16-gpu.onnx" -o src-tauri\models\kokoro-v1.0.fp16-gpu.onnx
          curl -L "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0/voices-v1.0.bin" -o src-tauri\models\voices-v1.0.bin

      - name: Build Tauri
        run: bun run tauri build

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: windows-bundle
          path: src-tauri/target/release/bundle/